name: "linting"

on:
  workflow_call:

permissions:
  pull-requests: read

jobs:
  linting-pr:
    name: validate pr title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            fix
            feat
            chore
          ignoreLabels: |
            autorelease
            dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint
        with:
          tflint_version: v0.47.0

      - name: Run TFLint
        run: tflint -f compact
