name: "linting"

on:
  workflow_call:

permissions:
  pull-requests: read

jobs:
  validate-pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            fix
            feat
            chore
          ignoreLabels: |
            autorelease
            dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-tflint:
    name: Run TFLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint
        with:
          tflint_version: v0.47.0

      - name: Run TFLint
        run: tflint -f compact
